language: r
cache: packages

matrix:
  include:
    - r: release
    - r: oldrel
    - r: devel
  allow_failures:
    - r: oldrel
    - r: devel
  fast_finish: true

branches:
  only:
    - master

env:
  global:
    - LINTR_COMMENT_BOT=true

github_packages:
  - acidgenomics/lintr

after_success:
  - test $TRAVIS_OS_NAME = 'linux' && $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'lintr::lint_package()'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
