# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# https://github.com/varemo/GSA_tutorial/blob/master/.travis.yml

language: general

# language: r
# sudo: required

services:
  - docker

# https://cloud.docker.com/u/acidgenomics/repository/docker/acidgenomics/bioc-release
before_install:
  - docker pull acidgenomics/bioc-release:20190414

script:
  # - docker run -v R CMD build .
  # - docker run -v R CMD check .
  - Rscript -e 'devtools::check()'
  - Rscript -e 'BiocCheck::BiocCheck(".", quit-with-status = TRUE)'
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::report()'
