# https://www.bioconductor.org/help/docker/#running
# https://docs.travis-ci.com/user/docker/
# https://www.jimhester.com/2017/10/13/docker/
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# https://github.com/varemo/GSA_tutorial/blob/master/.travis.yml

language: general

services:
  - docker

before_install:
  - docker pull acidgenomics/bioc-release
  - docker images
  - pwd
  - chmod +x travis-docker.sh

script:
  - docker run -ti --user bioc -v $PWD:/travis acidgenomics/bioc-release bash /travis/travis-docker.sh
