language: general

services:
  - docker

branches:
  only:
    - master

before_install:
  - env | sort
  - chmod +x travis-docker.sh

jobs:
  include:
    - stage: test
      name: "basejump"
      script: ./travis-docker.sh

after_failure:
  - df -h

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
