language: general

services:
  - docker

jobs:
  include:
    - stage: test
      name: "basejump-latest"
      script:
        - chmod +x travis-docker.sh
        - ./travis-docker.sh

after_failure:
  - df -h

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
