language: general

services:
  - docker

jobs:
  include:
    - stage: test
      name: "bioc-3.8"
      script:
        - docker pull acidgenomics/bioconductor:3.8
        - docker run -ti --volume="$PWD:/acidtest" --workdir="/acidtest" acidgenomics/bioconductor:3.8 Rscript -e 'source("travis-docker.R")'

notifications:
  email:
    recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: change
