# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb
# https://www.jimhester.com/2017/10/13/docker/
# https://github.com/varemo/GSA_tutorial/blob/master/.travis.yml

language: general

services:
  - docker

env:
  global:
    - IMAGE="${IMAGE}"

before_install:
  - docker pull "acidgenomics/${IMAGE}"

script:
  - docker run -v "$(pwd)":"/opt/$(basename $(pwd))" -it "$IMAGE" /bin/bash
  - cd /opt/acidtest
  - R CMD build .
  - R CMD check *tar.gz
